# Copyright 2026 Fractalyze Authors.
# SPDX-License-Identifier: Apache-2.0

name: "ZK Benchmark"
description: "Run benchmarks, detect regressions, and report results"
author: "Fractalyze"

branding:
  icon: "activity"
  color: "blue"

inputs:
  benchmark_cmd:
    description: "Command to run the benchmark (must output JSON to benchmark_results.json)"
    required: true
  implementation:
    description: "Implementation name (e.g., whir-zorch, plonky3)"
    required: true
  regression_threshold:
    description: "Regression threshold as decimal (e.g., 0.10 for 10%)"
    required: false
    default: "0.10"
  baseline_path:
    description: "Path to baseline JSON file for regression detection"
    required: false
    default: "benchmark_data/baseline.json"
  results_file:
    description: "Path to output benchmark results JSON"
    required: false
    default: "benchmark_results.json"
  slack_webhook:
    description: "Slack webhook URL for regression alerts"
    required: false
    default: ""
  store_results:
    description: "Whether to store results (true on main branch)"
    required: false
    default: "false"
  results_dir:
    description: "Directory to store historical results"
    required: false
    default: "benchmark_data"
  cpu_load_threshold:
    description: "CPU load threshold (0-1) above which to emit warning"
    required: false
    default: "0.80"
  memory_threshold:
    description: "Memory usage threshold (0-1) above which to emit warning"
    required: false
    default: "0.80"
  rolling_window:
    description: "Number of historical results to average for baseline"
    required: false
    default: "5"
  anthropic_api_key:
    description: "Anthropic API key for Claude AI analysis"
    required: false
    default: ""
  ai_model:
    description: "Claude model to use for analysis"
    required: false
    default: "claude-opus-4-5-20251101"
  dashboard_token:
    description: "GitHub token for triggering dashboard updates"
    required: false
    default: ""
  dashboard_repo:
    description: "Dashboard repository (owner/repo)"
    required: false
    default: "fractalyze/benchmark-dashboard"

outputs:
  has_regression:
    description: "Whether a regression was detected"
    value: ${{ steps.regression.outputs.has_regression }}
  results_file:
    description: "Path to benchmark results JSON"
    value: ${{ inputs.results_file }}
  cpu_load:
    description: "Normalized CPU load (0-1)"
    value: ${{ steps.system_load.outputs.cpu_load }}
  memory_usage:
    description: "Memory usage ratio (0-1)"
    value: ${{ steps.system_load.outputs.memory_usage }}

runs:
  using: "composite"
  steps:
    - name: Check system load
      id: system_load
      shell: bash
      env:
        CPU_LOAD_THRESHOLD: ${{ inputs.cpu_load_threshold }}
        MEMORY_THRESHOLD: ${{ inputs.memory_threshold }}
        SYSTEM_LOAD_OUTPUT: system_load.json
      run: python3 ${{ github.action_path }}/scripts/check_system_load.py

    - name: Run benchmark
      shell: bash
      run: ${{ inputs.benchmark_cmd }}

    - name: Verify test vectors
      shell: bash
      run: |
        python3 ${{ github.action_path }}/scripts/verify_test_vectors.py \
          --results="${{ inputs.results_file }}"

    - name: Detect regression
      id: regression
      shell: bash
      env:
        REGRESSION_THRESHOLD: ${{ inputs.regression_threshold }}
        BASELINE_PATH: ${{ inputs.baseline_path }}
        RESULTS_FILE: ${{ inputs.results_file }}
      run: |
        python3 ${{ github.action_path }}/scripts/detect_regression.py

    - name: AI performance analysis
      if: inputs.anthropic_api_key != ''
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        AI_MODEL: ${{ inputs.ai_model }}
        REGRESSION_THRESHOLD: ${{ inputs.regression_threshold }}
        BASELINE_PATH: ${{ inputs.baseline_path }}
        RESULTS_FILE: ${{ inputs.results_file }}
        AI_ANALYSIS_OUTPUT: ai_analysis.md
      run: python3 ${{ github.action_path }}/scripts/ai_analysis.py >> $GITHUB_STEP_SUMMARY

    - name: Store results
      if: inputs.store_results == 'true'
      shell: bash
      env:
        RESULTS_DIR: ${{ inputs.results_dir }}
        RESULTS_FILE: ${{ inputs.results_file }}
        ROLLING_WINDOW: ${{ inputs.rolling_window }}
      run: |
        mkdir -p "$RESULTS_DIR"
        TIMESTAMP=$(date -u +%Y%m%dT%H%M%S)
        cp "$RESULTS_FILE" "$RESULTS_DIR/${TIMESTAMP}.json"
        python3 ${{ github.action_path }}/scripts/calculate_rolling_baseline.py

    - name: Push results to dashboard
      if: inputs.store_results == 'true' && inputs.dashboard_token != ''
      shell: bash
      env:
        DASHBOARD_TOKEN: ${{ inputs.dashboard_token }}
        DASHBOARD_REPO: ${{ inputs.dashboard_repo }}
        IMPLEMENTATION: ${{ inputs.implementation }}
        RESULTS_FILE: ${{ inputs.results_file }}
      run: python3 ${{ github.action_path }}/scripts/push_to_dashboard.py

    - name: Send Slack alert
      if: failure() || steps.regression.outputs.has_regression == 'true'
      shell: bash
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook }}
        RESULTS_FILE: ${{ inputs.results_file }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        AI_ANALYSIS_OUTPUT: ai_analysis.md
      run: |
        if [ -n "$SLACK_WEBHOOK_URL" ]; then
          python3 ${{ github.action_path }}/scripts/send_slack_alert.py
        else
          echo "SLACK_WEBHOOK_URL not set, skipping alert"
        fi

    - name: Post summary
      shell: bash
      env:
        RESULTS_FILE: ${{ inputs.results_file }}
        SYSTEM_LOAD_OUTPUT: system_load.json
      run: |
        python3 ${{ github.action_path }}/scripts/post_summary.py >> $GITHUB_STEP_SUMMARY

    - name: Trigger dashboard update
      if: inputs.store_results == 'true' && inputs.dashboard_token != ''
      shell: bash
      env:
        DASHBOARD_TOKEN: ${{ inputs.dashboard_token }}
        DASHBOARD_REPO: ${{ inputs.dashboard_repo }}
        IMPLEMENTATION: ${{ inputs.implementation }}
      run: |
        curl -s -X POST \
          -H "Authorization: token $DASHBOARD_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$DASHBOARD_REPO/dispatches" \
          -d "{\"event_type\":\"deploy-pages\",\"client_payload\":{\"implementation\":\"$IMPLEMENTATION\"}}"
        echo "Triggered dashboard update for $IMPLEMENTATION"
